### ISSUE TITLE
Email should be a required field with two messages showing 

### ISSUE THREAD

**Issue by ztianai** [CJosephPollock/teamChallengeGroup1#6]

**Comment by ztianai** [comment]
If the email address is left blank after the user touches it, you form should show an appropriate error message. If it has a value but it's not a valid email address, you form should display a different appropriate error message.

**Comment by CJosephPollock** [comment]
This has been resolved.  The email field if touched shows the message "We need to know your email!" and if it is not a valid email (Ex. if you enter "blah" with no @ ) it will say "Enter a valid email."
